### ISSUE TITLE
Loader should handle 500 errors

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/cgp-dss-data-loader#28]
running the pip installed loader threw some weird loading errors. My first guess is that this is because of credentials, but either way there could be a problem. On second glance, maybe it just needs a better way to handle 500 errors.

```
 dssload --no-dry-run --dss-endpoint https://commons-dss.ucsc-cgp.org/v1 --staging-bucket commons-dss-upload standard --json-input-file transformed.json 
2018-07-05 14:33:42,527 - loader.standard_loader - INFO - Going to load 107 bundles
2018-07-05 14:33:42,527 - loader.standard_loader - INFO - Attempting to load bundle 1
2018-07-05 14:33:42,527 - loader.standard_loader - INFO - Attempting to load bundle with uuid 95e1d3f1-3a31-4c08-b637-a295fd72fadd
2018-07-05 14:33:46,986 - loader.standard_loader - ERROR - Error loading bundle 95e1d3f1-3a31-4c08-b637-a295fd72fadd
Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 6 more times]
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/43485e18-00ef-4871-8ae9-63e1f5b380aa (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 114, in load_all_bundles
    self._load_bundle(*parsed_bundle)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 71, in _load_bundle
    bundle_uuid)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 418, in load_dict
    return self.dss_uploader.upload_dict_as_file(metadata, filename, str(uuid.uuid4()), bundle_uuid, file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 228, in upload_dict_as_file
    content_type=content_type)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 253, in upload_local_file
    file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 365, in _upload_tagged_cloud_file_to_dss_by_copy
    response = self.dss_client.put_file._request(request_parameters)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/hca/util/__init__.py", line 135, in _request
    timeout=self.timeout_policy)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/43485e18-00ef-4871-8ae9-63e1f5b380aa (Caused by ResponseError('too many 500 error responses',))
2018-07-05 14:33:46,989 - loader.standard_loader - INFO - Attempting to load bundle 2
2018-07-05 14:33:46,990 - loader.standard_loader - INFO - Attempting to load bundle with uuid 559861bd-c066-47c8-993d-7e0a8ab21ad4
2018-07-05 14:33:49,981 - loader.standard_loader - ERROR - Error loading bundle 559861bd-c066-47c8-993d-7e0a8ab21ad4
Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 6 more times]
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/c18b94c0-8786-4b95-9c24-f0e866d086d1 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 114, in load_all_bundles
    self._load_bundle(*parsed_bundle)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 71, in _load_bundle
    bundle_uuid)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 418, in load_dict
    return self.dss_uploader.upload_dict_as_file(metadata, filename, str(uuid.uuid4()), bundle_uuid, file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 228, in upload_dict_as_file
    content_type=content_type)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 253, in upload_local_file
    file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 365, in _upload_tagged_cloud_file_to_dss_by_copy
    response = self.dss_client.put_file._request(request_parameters)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/hca/util/__init__.py", line 135, in _request
    timeout=self.timeout_policy)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/c18b94c0-8786-4b95-9c24-f0e866d086d1 (Caused by ResponseError('too many 500 error responses',))
2018-07-05 14:33:49,983 - loader.standard_loader - INFO - Attempting to load bundle 3
2018-07-05 14:33:49,984 - loader.standard_loader - INFO - Attempting to load bundle with uuid c68c97e3-0ff5-44e1-b1d4-6ac4ac66792b
2018-07-05 14:33:53,063 - loader.standard_loader - ERROR - Error loading bundle c68c97e3-0ff5-44e1-b1d4-6ac4ac66792b
Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 6 more times]
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/294e092e-f9b4-4c1d-ba4e-de8e0f039a84 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 114, in load_all_bundles
    self._load_bundle(*parsed_bundle)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 71, in _load_bundle
    bundle_uuid)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 418, in load_dict
    return self.dss_uploader.upload_dict_as_file(metadata, filename, str(uuid.uuid4()), bundle_uuid, file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 228, in upload_dict_as_file
    content_type=content_type)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 253, in upload_local_file
    file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 365, in _upload_tagged_cloud_file_to_dss_by_copy
    response = self.dss_client.put_file._request(request_parameters)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/hca/util/__init__.py", line 135, in _request
    timeout=self.timeout_policy)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/294e092e-f9b4-4c1d-ba4e-de8e0f039a84 (Caused by ResponseError('too many 500 error responses',))
2018-07-05 14:33:53,065 - loader.standard_loader - INFO - Attempting to load bundle 4
2018-07-05 14:33:53,065 - loader.standard_loader - INFO - Attempting to load bundle with uuid 849f5ddd-49ef-4b39-9f59-d588b510bc40
2018-07-05 14:33:56,079 - loader.standard_loader - ERROR - Error loading bundle 849f5ddd-49ef-4b39-9f59-d588b510bc40
Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 6 more times]
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/8794e445-3608-4fee-a752-f221ea1c4aa8 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 114, in load_all_bundles
    self._load_bundle(*parsed_bundle)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 71, in _load_bundle
    bundle_uuid)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 418, in load_dict
    return self.dss_uploader.upload_dict_as_file(metadata, filename, str(uuid.uuid4()), bundle_uuid, file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 228, in upload_dict_as_file
    content_type=content_type)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 253, in upload_local_file
    file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 365, in _upload_tagged_cloud_file_to_dss_by_copy
    response = self.dss_client.put_file._request(request_parameters)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/hca/util/__init__.py", line 135, in _request
    timeout=self.timeout_policy)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='commons-dss.ucsc-cgp.org', port=443): Max retries exceeded with url: /v1/files/8794e445-3608-4fee-a752-f221ea1c4aa8 (Caused by ResponseError('too many 500 error responses',))
2018-07-05 14:33:56,082 - loader.standard_loader - INFO - Attempting to load bundle 5
2018-07-05 14:33:56,082 - loader.standard_loader - INFO - Attempting to load bundle with uuid 22237aa5-712f-4f49-bb60-e12a1ea94999
^C2018-07-05 14:33:59,430 - loader.standard_loader - ERROR - Loading canceled with keyboard interrupt
Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 114, in load_all_bundles
    self._load_bundle(*parsed_bundle)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/standard_loader.py", line 71, in _load_bundle
    bundle_uuid)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 418, in load_dict
    return self.dss_uploader.upload_dict_as_file(metadata, filename, str(uuid.uuid4()), bundle_uuid, file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 228, in upload_dict_as_file
    content_type=content_type)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 253, in upload_local_file
    file_version=file_version)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/loader/base_loader.py", line 365, in _upload_tagged_cloud_file_to_dss_by_copy
    response = self.dss_client.put_file._request(request_parameters)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/hca/util/__init__.py", line 135, in _request
    timeout=self.timeout_policy)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 6 more times]
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/jesse/deleteme/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
2018-07-05 14:33:59,437 - loader.standard_loader - WARNING - Did not yet attempt to load 103 bundles
2018-07-05 14:33:59,438 - loader.standard_loader - ERROR - Could not parse 0 bundles
2018-07-05 14:33:59,438 - loader.standard_loader - ERROR - Could not load 4 bundles
2018-07-05 14:33:59,438 - loader.standard_loader - INFO - Successfully loaded 0 bundles

```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/LOAD-33)
┆Project Name: CGP-Data Loader
┆Issue Number: LOAD-33
┆Sprint: Lighthouse Sprint 31 Eblis
┆Epic: Loader Improvements

**Comment by jessebrennan** [comment]
On more consideration, this is really just AWS screwing up. Getting the errors here like this is actually not bad. I don't think that this is actually an issue any more. Closing :)
